angular.module('comss.dashboard').controller 'NFController', ($scope, FileUploader)->
  uploader = $scope.uploader = new FileUploader(url: 'upload.php')
  # FILTERS
  # a sync filter
  uploader.filters.push
    name: 'syncFilter'
    fn: (item, options) ->
      console.log 'syncFilter'
      @queue.length < 10
  # an async filter
  uploader.filters.push
    name: 'asyncFilter'
    fn: (item, options, deferred) ->
      console.log 'asyncFilter'
      setTimeout deferred.resolve, 1e3
      return
  # CALLBACKS

  uploader.onWhenAddingFileFailed = (item, filter, options) ->
    console.info 'onWhenAddingFileFailed', item, filter, options
    return

  uploader.onAfterAddingFile = (fileItem) ->
    console.info 'onAfterAddingFile', fileItem
    return

  uploader.onAfterAddingAll = (addedFileItems) ->
    console.info 'onAfterAddingAll', addedFileItems
    return

  uploader.onBeforeUploadItem = (item) ->
    console.info 'onBeforeUploadItem', item
    return

  uploader.onProgressItem = (fileItem, progress) ->
    console.info 'onProgressItem', fileItem, progress
    return

  uploader.onProgressAll = (progress) ->
    console.info 'onProgressAll', progress
    return

  uploader.onSuccessItem = (fileItem, response, status, headers) ->
    console.info 'onSuccessItem', fileItem, response, status, headers
    return

  uploader.onErrorItem = (fileItem, response, status, headers) ->
    console.info 'onErrorItem', fileItem, response, status, headers
    return

  uploader.onCancelItem = (fileItem, response, status, headers) ->
    console.info 'onCancelItem', fileItem, response, status, headers
    return

  uploader.onCompleteItem = (fileItem, response, status, headers) ->
    console.info 'onCompleteItem', fileItem, response, status, headers
    return

  uploader.onCompleteAll = ->
    console.info 'onCompleteAll'
    return

  console.info 'uploader', uploader

  # ---
  # generated by js2coffee 2.2.0
  return